### ISSUE TITLE
Miss data files

### ISSUE THREAD

**Issue by Roderick-Stinson** [florin-git/The-Power-of-Noise#3]
I notice that there are many usages like "data/processed/corpus_with_random_at60.json" in your code. But there isn't any json file in data/processed folder. Can you upload all the missing data files ?

**Comment by florin-git** [comment]
Hi, thank you for your comment.
As mentioned in the README, files that are too large to be uploaded directly to the repository are stored in this [Google Drive](https://drive.google.com/drive/folders/1MfR7mJ76tyVpjbMwUkMVbEjOQKpdL-Lq?usp=sharing) folder.
If you have any trouble accessing the files or need any further clarification, please don't hesitate to ask.
