### ISSUE TITLE
Missing File "wiki_dec_2018.json"

### ISSUE THREAD

**Issue by haowei-freesky** [florin-git/The-Power-of-Noise#4]
Thank you for your great work, really interesting findings!

I plan to verify the conclusions on other datasets (e.g. TriviaQA), so I have to begin with retrieval. The file "wiki_dec_2018.json" in the script [run_compute_corpus_embedding.sh](https://github.com/florin-git/The-Power-of-Noise/blob/main/example_scripts/run_compute_corpus_embeddings.sh) might be missing, given that I have searched in this repo, HF and Google drive but not found.

If you could help me find the missing file or give me some hints about conducting experiments on other datasets, I would really appreciate it.

**Comment by florin-git** [comment]
Thank you for your interest in the work and for planning to extend the research!

Regarding the file “wiki_dec_2018.json”, it's simply the name I used for the “corpus.json” file to indicate which wiki dump version was employed. I realize now that I used “corpus.json” in other scripts as well, which could be confusing. To maintain consistency, I’ll update the filename to “corpus.json” in the ‘run_compute_corpus_embeddings.sh’ script.

Thank you for bringing this to my attention!
